/* Compra e Venda de Gado — v96 fixes */
(function(){
  window.APP_WEB_VERSION='96';
  function dataUrlToBlob(dataUrl){var p=String(dataUrl||'').split(',');if(p.length<2)throw new Error('PDF sem conteúdo válido');var meta=p[0]||'';var mime=(meta.match(/data:([^;]+)/)||[])[1]||'application/pdf';var bin=meta.indexOf(';base64')>=0?atob(p.slice(1).join(',')):decodeURIComponent(p.slice(1).join(','));var bytes=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i)&255;return new Blob([bytes],{type:mime});}
  window.__pdfDocsV85=window.__pdfDocsV85||{};
  window.openStoredPdfV85=function(id){try{var doc=window.__pdfDocsV85[id];if(!doc||!doc.data)throw new Error('Documento não encontrado');var name=doc.name||'documento.pdf';if(window.AndroidPdf&&typeof window.AndroidPdf.openPdf==='function'){window.AndroidPdf.openPdf(doc.data,name);return;}var blob=dataUrlToBlob(doc.data);var url=URL.createObjectURL(blob);var w=window.open(url,'_blank');if(!w){var a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();}setTimeout(function(){try{URL.revokeObjectURL(url)}catch(e){}},60000);}catch(e){alert('Não foi possível abrir o PDF: '+(e.message||e));}};
  window.fileLink=function(doc,label){if(!doc||!doc.data)return '—';var id='pdf96_'+Math.random().toString(36).slice(2)+Date.now().toString(36);window.__pdfDocsV85[id]=doc;return '<button type="button" class="mini" onclick="openStoredPdfV85(\''+id+'\')">Abrir PDF</button>';};
  var TOMBSTONE_KEY='gado_deleted_records_permanent_v95',LEGACY_PENDING='gado_pending_sync_v78',LEGACY_RETRY='gado_sync_retry_v78',sync96Busy=false,sync96Timer=null,lastPullAt=0;
  function tombstones(){try{return JSON.parse(userGet(TOMBSTONE_KEY)||'[]')||[];}catch(e){return [];}}
  function saveTombstones(a){try{userSet(TOMBSTONE_KEY,JSON.stringify(Array.from(new Set(a||[]))));}catch(e){}}
  function mergeDeleted(remote){var all=Array.from(new Set(tombstones().concat(Array.isArray(remote)?remote:[])));saveTombstones(all);return all;}
  function addTombstone(id){if(!id)return;var a=tombstones();if(a.indexOf(id)<0)a.push(id);saveTombstones(a);}
  function applyDeleted(remote){var all=mergeDeleted(remote),d=new Set(all);records=records.filter(function(r){return !d.has(r&&r.id);});try{userSet(KEY,JSON.stringify(records));}catch(e){}return all;}
  function stable(v){try{return JSON.stringify(v||[]);}catch(e){return '[]';}}
  function clearConfirmedFlags(){try{userRemove(OFFLINE_DIRTY_KEY);userRemove(DELETED_RECORDS_KEY);userRemove(DELETED_COSTS_KEY);userRemove(LEGACY_PENDING);localStorage.removeItem(LEGACY_RETRY);}catch(e){}}
  function markSynced(){setCloudStatus('Sincronizado ✓','ok');var s=document.getElementById('saveStatus');if(s)s.textContent='Dados sincronizados • '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});var o=document.getElementById('offlineStatus');if(o){o.textContent='Online • sincronizado';o.className='cloudpill ok';}var b=document.getElementById('syncNowBtn');if(b)b.style.display='none';}
  function hasPending(){try{return isOfflineDirty()||!!userGet(LEGACY_PENDING)||getDeletedIds(DELETED_RECORDS_KEY).length>0||getDeletedIds(DELETED_COSTS_KEY).length>0;}catch(e){return false;}}
  window.delRecord=function(id){if(!confirm('Excluir esta negociação?'))return;addTombstone(id);try{addDeletedId(DELETED_RECORDS_KEY,id);}catch(e){}try{costs.filter(function(c){return c.recordId===id;}).forEach(function(c){addDeletedId(DELETED_COSTS_KEY,c.id);});}catch(e){}records=records.filter(function(x){return x.id!==id;});costs=costs.filter(function(c){return c.recordId!==id;});try{markOfflineDirty();}catch(e){}persist();renderAll();try{autoExcelBackup();}catch(e){}if(navigator.onLine)setTimeout(function(){window.syncPendingNow(true);},100);};
  async function save96(){if(!sb||!cloudUser)return false;if(!navigator.onLine){try{markOfflineDirty();}catch(e){}setCloudStatus('Offline • pendente','warn');return false;}if(sync96Busy)return false;sync96Busy=true;try{var dels=applyDeleted();var payload={user_id:cloudUser.id,records:records,costs:costs,deleted_records:dels,updated_at:new Date().toISOString()};var res=await sb.from(CLOUD_TABLE).upsert(payload,{onConflict:'user_id'}).select('user_id,records,costs,deleted_records,updated_at').single();if(res.error)throw res.error;if(!res.data||res.data.user_id!==cloudUser.id)throw new Error('Nuvem não confirmou o usuário');var rd=Array.isArray(res.data.deleted_records)?res.data.deleted_records:[],ds=new Set(rd);for(var i=0;i<dels.length;i++)if(!ds.has(dels[i]))throw new Error('Nuvem não confirmou exclusões');clearConfirmedFlags();markSynced();return true;}catch(e){try{markOfflineDirty();}catch(_){}setCloudStatus('Pendente de sincronização','warn');console.error('SYNC96 SAVE',e);return false;}finally{sync96Busy=false;}}
  async function load96(force){if(!sb||!cloudUser||!navigator.onLine)return false;if(sync96Busy)return false;if(!force&&Date.now()-lastPullAt<5000)return true;sync96Busy=true;lastPullAt=Date.now();try{var pendingBefore=hasPending();var res=await sb.from(CLOUD_TABLE).select('records,costs,deleted_records,updated_at').eq('user_id',cloudUser.id).maybeSingle();if(res.error)throw res.error;if(!res.data){sync96Busy=false;return await save96();}var deleted=applyDeleted(Array.isArray(res.data.deleted_records)?res.data.deleted_records:[]),cloudRecords=Array.isArray(res.data.records)?res.data.records:[],cloudCosts=Array.isArray(res.data.costs)?res.data.costs:[];records=mergeById(cloudRecords,records,deleted).filter(function(r){return deleted.indexOf(r&&r.id)<0;});costs=mergeById(cloudCosts,costs,getDeletedIds(DELETED_COSTS_KEY));userSet(KEY,JSON.stringify(records));userSet(COSTKEY,JSON.stringify(costs));renderAll();var cloudDeleted=Array.isArray(res.data.deleted_records)?res.data.deleted_records:[];var needsPush=pendingBefore||stable(records)!==stable(cloudRecords.filter(function(r){return deleted.indexOf(r&&r.id)<0;}))||stable(costs)!==stable(cloudCosts)||stable(deleted)!==stable(cloudDeleted);sync96Busy=false;if(needsPush)return await save96();clearConfirmedFlags();markSynced();return true;}catch(e){console.error('SYNC96 LOAD',e);setCloudStatus('Pendente de sincronização','warn');return false;}finally{sync96Busy=false;}}
  cloudSaveNow=save96;cloudLoad=function(){return load96(true);};scheduleCloudSave=function(){clearTimeout(sync96Timer);setCloudStatus('Salvando na nuvem…','warn');sync96Timer=setTimeout(save96,350);};window.syncPendingNow=async function(manual){if(!navigator.onLine){setCloudStatus('Offline • pendente','warn');return false;}if(hasPending())return save96();return load96(!!manual);};
  var originalInitCloud=window.initCloud,reconnectUntil=0;function keepUi(){try{if(typeof cloudUser!=='undefined'&&cloudUser&&typeof setAuthenticatedUI==='function')setAuthenticatedUI(true);}catch(e){}}
  async function recoverSession(tryNo){try{bootLoginApproved=true;}catch(e){}keepUi();try{if(typeof sb!=='undefined'&&sb&&navigator.onLine){var r=await sb.auth.getSession(),s=r&&r.data&&r.data.session;if(s&&s.user){try{cloudUser=s.user;}catch(e){}try{bootLoginApproved=true;}catch(e){}keepUi();await window.syncPendingNow(true);return true;}}catch(e){}if(Date.now()<reconnectUntil&&(tryNo||0)<8)setTimeout(function(){recoverSession((tryNo||0)+1);},800);return false;}
  window.initCloud=async function(){if(Date.now()<reconnectUntil){try{bootLoginApproved=true;}catch(e){}keepUi();recoverSession(0);return;}if(typeof originalInitCloud==='function')return originalInitCloud();};window.addEventListener('online',function(ev){reconnectUntil=Date.now()+10000;try{bootLoginApproved=true;}catch(e){}try{ev.stopImmediatePropagation();}catch(e){}keepUi();setTimeout(function(){recoverSession(0);},250);},true);window.addEventListener('pageshow',function(){applyDeleted();try{if(typeof cloudUser!=='undefined'&&cloudUser){bootLoginApproved=true;keepUi();}}catch(e){}},true);
  function forceVersion(){try{document.body.setAttribute('data-app-version','96');document.title='Compra e Venda de Gado — v96';var h=document.querySelector('header h1');if(h){var spans=h.querySelectorAll('span');var found=false;spans.forEach(function(s){if(/^v\d+$/i.test((s.textContent||'').trim())){s.textContent='v96';found=true;}});if(!found){var b=document.createElement('span');b.textContent='v96';b.style.cssText='font-size:12px;font-weight:800;padding:3px 7px;border-radius:999px;background:rgba(255,255,255,.16);vertical-align:middle;white-space:nowrap;margin-left:6px';h.appendChild(b);}}}catch(e){}}
  function refresh(){forceVersion();applyDeleted();try{if(typeof renderTable==='function')renderTable();}catch(e){}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh);else refresh();setTimeout(refresh,500);setTimeout(refresh,1500);
})();
